### ISSUE TITLE
can't use stronghold with tauri v2

### ISSUE THREAD

**Issue by sekomer** [tauri-apps/plugins-workspace#2062]
I was able to use stronghold in my project, after migrating to v2, I'm unable to use the stronghold, I see this error in inspect console after initializing the stronghold

```
Unhandled Promise Rejection: TypeError: window.__TAURI_IPC__ is not a function. (In 'window.__TAURI_IPC__({
      cmd,
      callback,
      error,
      ...args
    })', 'window.__TAURI_IPC__' is undefined)
```

example source code of what im doing

```ts
import { Client, Stronghold } from "tauri-plugin-stronghold-api";
import { appDataDir } from "@tauri-apps/api/path";

const StrongholdPage: React.FC = () => {
  const [value, setValue] = useState("");

  useEffect(() => {
    const initStronghold = async () => {
      const vaultPath = `${await appDataDir()}/vault.hold`;
      const vaultPassword = "vault password";
      const stronghold = await Stronghold.load(vaultPath, vaultPassword);

      let client: Client;
      const clientName = "name your client";
      try {
        client = await stronghold.loadClient(clientName);
      } catch {
        client = await stronghold.createClient(clientName);
      }

      return {
        stronghold,
        client,
      };
    };

    // Insert a record to the store
    async function insertRecord(store: any, key: string, value: string) {
      const data = Array.from(new TextEncoder().encode(value));
      await store.insert(key, data);
    }

    // Read a record from store
    async function getRecord(store: any, key: string): Promise<string> {
      const data = await store.get(key);
      return new TextDecoder().decode(new Uint8Array(data));
    }

    const initStrongholdAsync = async () => {
      const { stronghold, client } = await initStronghold();

      const store = client.getStore();
      const key = "my_key";

      // Insert a record to the store
      insertRecord(store, key, "secret value");

      // Read a record from store
      const value = await getRecord(store, key);
      console.log(value); // 'secret value'

      // Save your updates
      await stronghold.save();

      // Remove a record from store
      await store.remove(key);
    };

    initStrongholdAsync();
  }, [value]);

  return (
    <div>
      <div>StrongholdPage</div>
      <button onClick={() => setValue(Math.random().toString())}>
        initStrongholdAsync
      </button>
    </div>
  );
};

export default StrongholdPage;
```

am I missing something here? (tauri newbie here)

**Comment by FabianLars** [comment]
This error should mean that the js package for the plugin is still v1. You can use the `tauri info` command for a quick check.

**Comment by sekomer** [comment]
@FabianLars I thought the same thing but then after updating nothing changed :D

**Comment by sekomer** [comment]
```
❯ yarn run info
yarn run v1.22.19
warning package.json: No license field
$ tauri info

[✔] Environment
    - OS: Mac OS 15.0.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.18.2
    - yarn: 1.22.19
    - npm: 9.8.1
    - bun: 1.0.18
    - deno: deno 2.0.6

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.0
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 2.1.0
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : not installed!
    - tauri-plugin-window-state 🦀: 2.0.2
    - @tauri-apps/plugin-window-state : not installed!
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - @tauri-apps/plugin-global-shortcut : not installed!
    - tauri-plugin-stronghold 🦀: 2.0.1
    - @tauri-apps/plugin-stronghold : 2.0.0
    - tauri-plugin-dialog 🦀: 2.0.3
    - @tauri-apps/plugin-dialog : not installed!
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-store 🦀: 2.1.0
    - @tauri-apps/plugin-store : not installed!
    - tauri-plugin-http 🦀: 2.0.3
    - @tauri-apps/plugin-http : not installed!
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-process 🦀: 2.0.1
    - @tauri-apps/plugin-process : not installed!
    - tauri-plugin-notification 🦀: 2.0.1
    - @tauri-apps/plugin-notification : not installed!
    - tauri-plugin-os 🦀: 2.0.1
    - @tauri-apps/plugin-os : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://127.0.0.1:4590/
    - framework: React
    - bundler: Rollup
✨  Done in 34.94s.
```

this is the info output

**Comment by FabianLars** [comment]
maybe delete node_modules and your frontend's build cache (if any)? `__TAURI_IPC__` was removed in early v2 alpha so this can really only be a version mismatch in some way 🤔

**Comment by sekomer** [comment]
finally solved, this maneuver cost us 3 hours 🥲 
just removed node modules, did cargo clean, was still getting same error 🤔

then I checked the package json and saw that I have both `"tauri-plugin-stronghold-api": "https://github.com/tauri-apps/tauri-plugin-stronghold#v1",` and `"@tauri-apps/plugin-stronghold": "^2.0.0",` which was causing trouble...

thanks for your help @FabianLars
